source 'https://rubygems.org'

gem 'eventmachine'
gem 'hx_cbor'
gem 'oj'
gem 'websocket-eventmachine-server'
#gem 'airbrake-ruby'
gem 'EXtremeZip' , '>= 2022.2.6'
gem 'get_process_mem'
gem 'tushare'
gem 'EventChart'
gem 'byebug'
gem 'memory_profiler'
gem 'stackprof'
